# Site settings
title: Mow and Grow
description: Beautiful landscaping services in your area.
url: "https://www.mow-and-grow.ca"
baseurl: ""
og_image: /assets/img/profile-pic.jpg
google_analytics: "" # Add your Google Analytics Tracking ID

# Header navigation
header:
  pages:
    - name: Home
      slug: /
    - name: Services
    - name: Gallery
    - name: Contact

# Footer settings
footer:
  show_powered_by: true
  contact:
    - type: email
      name: Email
      value: Devin.sherrard@gmail.com
    - type: phone
      name: Phone
      value: "+1-782-234-1027"
  follow: []

# Build settings
markdown: kramdown
sass:
  style: :compressed
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for cache busting
version: 1
