# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
title: Mow and Grow
description: Professional lawn care and landscaping services in Halifax, Nova Scotia. Quality maintenance for residential and commercial properties.
baseurl: ""
url: "https://www.mow-and-grow.ca"
og_image: /assets/img/lawn-service.jpg
google_analytics: ""
header:
  pages:
    - name: Home
      slug: /
    - name: Services
      slug: /services
    - name: Gallery
      slug: /gallery
    - name: Contact
      slug: /contact
footer:
  show_powered_by: true
  contact:
    - type: email
      name: Email
      value: info@mow-and-grow.ca
    - type: phone
      name: Phone
      value: "+1 (782) 234-1027"
      link: "tel:+17822341027"
  follow:
    - type: facebook
      name: Facebook
      link: https://facebook.com/mowandgrowca
    - type: instagram
      name: Instagram
      link: https://instagram.com/mowandgrowca
    - type: google
      name: Google Business
      link: https://g.page/mowandgrowca
# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
# Used for defeating caching
version: 1
